### ISSUE TITLE
Improve debug logging experience

### ISSUE THREAD

**Issue by mcmcgrath13** [JuliaServices/Rematch2.jl#60]
I'm debugging something, so added an @info log where I rely on the logging macro's automatic expansion of the arguments to keys and values.

this
```
@info "relvar empty" x x.attrs
```

logs
```
┌ Info: relvar empty
│   begin
    var"##42567"
end = F/Int64/Int64
└   (begin
    var"##42567"
end).attrs = SourceIdAttributes(true, false, missing)
```

You can see the code gen'ed variable name ends up in the logging. It would be nice if the keys expanded to the original variable name instead of the post-code-gen variable name.

With plain Julia logging expansion, I'd expect to see something like:
```
┌ Info: relvar empty
│   x = F/Int64/Int64
└   x.attrs = SourceIdAttributes(true, false, missing
```

**Comment by gafter** [comment]
See https://relationalai.atlassian.net/browse/RAI-14139.  Also see https://github.com/RelationalAI/raicode/pull/14422 and particularly https://github.com/RelationalAI/raicode/pull/14422/commits/b39aed1620ed19aba7a41233079d427516c1d924 which shows how to work around the issues that arise.

**Comment by gafter** [comment]
I could use some help deciding what to do about this.  Here is where we got to where we are today:

1. Existing matcher implementations were inconsistent about how they handle scoping.  When evaluating a programmer's expression (in three cases - an interpolation in a pattern, a `where` clause, and the result expression of a case), if there are pattern variables, they would be assigned in a `let` block surrounding the user code.  If there were no pattern variables to assign, there would be no enclosing block generated around that code.
2. That means that sometimes user code that contains an assignment would cause the variable to leak out into the enclosing context, and sometimes not.  That is annoying and presents an inconsistent experience to the programmer.  We should be consistent.
3. Another annoying thing is that people cannot assign in a `where` clause of a case and then use the resulting value in the result part.  So being consistent by closing the scope is not necessarily ideal.
4. One good way of being consistent is to let the programmer decide: if they use a `begin...end` block for the `@match` body, then user assignments inside leak out to the enclosing scope.  If they use `let...end`, then they do not leak out.
5. But we have to avoid having *pattern variables* leak out, especially since we assign to them tentatively in order to evaluate `where` clauses... even if the case fails.  We don't want these tentative assignments leaking out.
6. So to avoid leaking of pattern variables, they are mapped to an expression that evaluates to the value that pattern value would hold.  We do this by rewriting pattern variables to references to pattern-matching internal temporary variables.
7. But we cannot allow the user to modify these internal variables, as that would invalidate the invariants of the generated pattern-matching automaton.  So we rewrite `x` to `begin ##some_temp&&; end` instead.
8. That causes several issues:
  1. The debugging issue mentioned here.
  2. Because of the rewriting, you cannot [use the pattern variable for the name of a local function parameter](https://github.com/RelationalAI/raicode/pull/14212/files#diff-1e58512326e6b3d392e4482284fd2fe0456857c0cedbd9f15f1a0bd70acb4d25R636-R638).
  3. Also, see https://relationalai.atlassian.net/browse/RAI-14139

There are several approaches we might consider to addressing this:
1. Make them all *closed* scopes.  Always produce a `let...end` around user expressions.  Then we can assign to the pattern variables, and they will remain local variables of the correct name.
  1. Advantages: simplicity, and addresses problems 1, 2, and 3 above.
  2. Disadvantages: variables assigned in a `where` clause are not visible in the result part - users would be forced to pre-assign the variable to force it into an enclosing scope.
2. Make them all *open* scopes.  To hide the pattern variable values from enclosing scopes, we would assign `nothing` to them at the end of the evaluation of a user expression.  The variables would still be in scope, but contain `nothing`.
3. Either (1) or (2) depending on whether the user writes `begin...end` or `let...end`

I'm leaning toward (1) for simplicity.  I think the option of using `let...end` as a way of controlling this behavior is too subtle and not obvious.  Better to be simple in the semantics.

Note that, even after "fixing" this, you still might not have an ideal debugging experience.  Consider code such as this:

```julia
@match input begin
    SomePattern(x) where some_expression(x) && some_other_expression(x) => some_result(x)
    SomePattern(y) where some_expression(y) => some_result(y)
end
```

Currently, because of the rewriting step, `some_expression(x)` and `some_expression(y)` are seen as identical expressions.  That means they can be shared.  Consequently, if you set a breakpoint in that code, you would either not see `x` or not see `y` (currently, you see neither).  We can either
1. Treat them as different, so that they would not be shared, but the debugging experience would be better, or
2. Treat them as the same, which means we would (arbitrarily, from the programmer's point of view) decide what to call that intermediate variable.

Similarly, when you step through such code, you would see the line numbers corresponding to the arbitrary one that the compiler decided to evaluate (since the evaluation result is shared).  I don't think we can avoid this while still sharing the evaluations.

What are your thoughts?

**Comment by gafter** [comment]
I am leaning toward:
1. Making them all closed scopes.
2. Treat `some_expression(x)` and `some_expression(y)` as different, even if `x` and `y` represent otherwise identical patterns.

**Comment by mcmcgrath13** [comment]
I agree on `1. Making them all closed scopes` - it's annoying with the `where` clauses, but seems much more consistent overall.

I think the sharing evaluations is a fair trade for that behavior. As long as we document this, it doesn't really bother me at all.

**Comment by gafter** [comment]
@mcmcgrath13 

> I think the sharing evaluations is a fair trade for that behavior. As long as we document this, it doesn't really bother me at all.

Do you mean you prefer that we should share the evaluation of `x where some_expression(x)` and `y where some_expression(y)`, or do you mean that you prefer we get a good debugging experience, and require the user to rename the variables to be the same in order to get the sharing?  The latter is easier (already done, in fact), but the former is not too hard.

Now that I think of it, we probably don't even share the result of two expressions that appear identical like `begin something; end` which contain line number nodes, because the line number nodes would differ.  We probably should.
